#pragma once

#include <stdint.h>

// Standard eight-byte HID boot-keyboard report.
struct HidKeyboardReport
{
  uint8_t modifiers;
  uint8_t reserved;
  uint8_t keys[6];
};

// Converts a USB HID keyboard usage and Shift state to the ISO-7 value
// generated by the corresponding KC85 key. Returns false when the key has no
// KC85 equivalent.
bool hidUsageToIso7(uint8_t usage, bool shifted, uint8_t &iso7Code);
