#pragma once

#include <stdint.h>
#include <stddef.h>

// Normalized keyboard state used internally after decoding a HID input report.
struct HidKeyboardReport
{
  uint8_t modifiers;
  uint8_t reserved;
  uint8_t keys[6];
};

// Adds one report ID's current state to an aggregate. Modifiers are combined,
// duplicate keys are removed, and the first six distinct usages are retained.
void mergeKeyboardReport(HidKeyboardReport &aggregate,
                         const HidKeyboardReport &report);

// Converts a USB HID keyboard usage and Shift state to the ISO-7 value
// generated by the corresponding KC85 key. Returns false when the key has no
// KC85 equivalent.
bool hidUsageToIso7(uint8_t usage, bool shifted, uint8_t &iso7Code);

struct HidKeyboardEvent {
  // usage == 0 releases the active output; otherwise this is a new key-down.
  uint8_t usage;
  uint8_t iso7Code;
};

// Reports describe held keys, not new keystrokes. Remember their transitions
// and choose the most recently pressed supported key for KC85 autorepeat.
// A modifier change or the release of another key never replays a held key.
class HidKeyboardTransitions {
 public:
  static constexpr size_t MaxEvents = 7; // One release and six new keys.
  size_t update(const HidKeyboardReport &report,
                HidKeyboardEvent (&events)[MaxEvents]);
  void reset();

 private:
  HidKeyboardReport previous_{};
  uint8_t activeUsage_ = 0;
};
